packages:
  - api/
  - packages/*
catalog:
  eslint: 9.23.0
  eslint-config-unjs: ^0.4.2
  nitropack: ^2.11.7
  prettier: ^3.5.3
  "@antfu/ni": ^24.3.0
  typescript: ^5.8.2
  changelogen: ^0.5.7
  "@vitest/coverage-v8": ^3.0.5
  "unbuild": "^3.3.1"
  "vitest": "^3.0.5"
onlyBuiltDependencies:
  - esbuild
